#!/bin/bash
# Sawa-X — Auto-detect Canton node hash and update UI
# Run this after every sandbox restart: bash update-hash.sh

cd /mnt/c/Users/Lenovo/OneDrive/Desktop/sawa-x-demo

python3 << 'PYEOF'
import subprocess, base64, json, re, glob

# Get current hash from live ledger
result = subprocess.run(
    ['daml', 'ledger', 'list-parties', '--host', 'localhost', '--port', '6865'],
    capture_output=True, text=True
)
match = re.search(r'Admin::([a-f0-9]+)', result.stdout)
if not match:
    print("ERROR: Sandbox not running or Admin party not found")
    print(result.stdout[:200])
    exit(1)

NEW_HASH = match.group(1)
print(f"✅ Canton node hash: {NEW_HASH}")

# Build token with all 6 parties (3 investors)
parties = [
    f'Admin::{NEW_HASH}',
    f'Operator::{NEW_HASH}',
    f'Investor1::{NEW_HASH}',
    f'Investor2::{NEW_HASH}',
    f'Investor3::{NEW_HASH}',
    f'SPV_METALEX::{NEW_HASH}',
]

header = base64.urlsafe_b64encode(
    json.dumps({'alg': 'HS256', 'typ': 'JWT'}).encode()
).rstrip(b'=').decode()

payload = base64.urlsafe_b64encode(json.dumps({
    'https://daml.com/ledger-api': {
        'ledgerId': 'sandbox',
        'applicationId': 'sawa-x',
        'actAs':  parties,
        'readAs': parties,
    }
}).encode()).rstrip(b'=').decode()

TOKEN = f'{header}.{payload}.fake'
print(f"✅ Token built ({len(TOKEN)} chars)")

# Update all .ts and .tsx files
all_files = (
    glob.glob('ui/src/**/*.ts',  recursive=True) +
    glob.glob('ui/src/**/*.tsx', recursive=True)
)

updated = 0
for filepath in all_files:
    with open(filepath, 'r') as f:
        content = f.read()

    # Replace any old Canton hash
    new_content = re.sub(r'1220[a-f0-9]{60,70}', NEW_HASH, content)

    # Update token in ledger.ts
    if 'ledger.ts' in filepath:
        # The ledger.ts now builds token dynamically — no static token to replace
        pass

    if new_content != content:
        with open(filepath, 'w') as f:
            f.write(new_content)
        print(f"   Updated: {filepath}")
        updated += 1

# Also write hash to localStorage seed file for UI
seed_path = 'ui/src/api/canton-hash.ts'
with open(seed_path, 'w') as f:
    f.write(f"// Auto-generated by update-hash.sh — do not edit\n")
    f.write(f"export const CANTON_HASH = '{NEW_HASH}';\n")
print(f"   Written: {seed_path}")

print(f"\n✅ Done! Updated {updated} files with hash: {NEW_HASH[:20]}…")
print("   Now press Ctrl+Shift+R in the browser")
print(f"\n   Or paste this in browser console to set hash instantly:")
print(f"   localStorage.setItem('canton_node_hash', '{NEW_HASH}')")
PYEOF
