canton {
  participants {
    participant1 {
      storage {
        type = memory
      }
      admin-api {
        port = 6866
      }
      ledger-api {
        port = 6865
      }
    }
  }

  domains {
    local {
      storage {
        type = memory
      }
      public-api {
        port = 6867
      }
      admin-api {
        port = 6868
      }
    }
  }
}
